### PR TITLE
Fix path of AC status in /sys

### PR DESCRIPTION
**Pull request by jo-so**

### CODE REVIEW

**Comment by coldfix** [comment]
Hi, `AC` is the correct prefix for some systems (e.g. at least 3 laptops I used this with so far), so you should add `AC0` as a fallback option instead, just as it was done for `ACAD` -- rather than replacing `AC` entirely.

**Comment by jo-so** [comment]
Okay. Is the kernel version on these laptops up to date? I've saw, the power adapter on Android is named *ac* (lower case). I seems there's no uniform naming of the power adapter. What do you think about something like `io.popen("grep -F 1 "..pow.."/*/online")`.

**Comment by coldfix** [comment]
I'm using archlinux so I believe that is usually the most up to date stable kernel version you get.

> I've saw, the power adapter on Android is named ac (lower case). I seems there's no uniform naming of the power adapter. What do you think about something like `io.popen("grep -F 1 "..pow.."/*/online")`.

Interesting, I'll have to consider, but I kinda dislike the indiscriminate wildcard. Can we at least rely on the name starting with AC/ac?

**Comment by jo-so** [comment]
Unfortunately, Lua doesn't have functions to read the directory content. I've grepped through the kernel source and found no indication, that the name starts with AC/ac. The only thing is the *online* file in the directory.

**Comment by coldfix** [comment]
lua stdlib doesn't have directory listings, but you could easily do something like

```lua
for line in io.popen("ls -1 " .. pow):lines() do
  if line:lower():match("ac") then
    ....
  end
end
```

BTW: the `discover` function in this module does the same.

Ok, so the options are:

1. hardcode `AC`, `AC0`, `ac`, `ACAD` as is done right now
2. add constructor argument that allows the user to specify the adapter name explicitly
3. use wildcard like you suggested
4. based on directory listing as above, matching name ac

Drawbacks:
1. it's likely that we miss some posssibility, so this may not work for some people, which may pose an obstactle
2. inconvenient / obstacle for users
3. there could be problems if there is another interface with an `online` file (unlikely?)
4. as you say, the adapter could be named differently

In the end, any of these options is probably fine, so you can pick the one that you prefer.

**Comment by jo-so** [comment]
I don't see an advantage of running the subprocess *ls* over calling the *grep*. Where's the difference?

The *grep* with the wildcard doesn't have problems, if there are more than one interface with *online*; `read('*n')` reads up to the first newline and ignores the remaining content. The call checks if there's at least one interface have the *online* attribute with 1. Having zero or more than one matches is handled fine by the code.

**Comment by jo-so** [comment]
That's the full snippet, I would propose:
```
    local grep_out = io.popen("grep -F 1 "..pow.."/*/online")
    r.ac_state = grep_out:read("*n") or 0
    grep_out:close()
```

**Comment by coldfix** [comment]
> I don't see an advantage of running the subprocess ls over calling the grep. Where's the difference?

1. I can't find any official statement that `io.popen` supports shell syntax like wildcards. Then again, there is nothing really other than "This function is system dependent and is not available on all platforms", so there is no guarantee for anything.

2. The discovery of battery adapters in the same module is already done with the `ls` and `string.match`. Using a different mechanism (grep + wildcard) for a very similar job (discovery of AC adapter), may create a cognitive dissonance that can make readers wonder whether there was any particular reason not to just use the same tool again, and at least it will (very slightly) increase the amount of mental space required to understand the whole module for no obvious reason.

3. The possibility to filter for `AC` prefix if there is *another interface* that happens to also expose an `online` property (I'm not talking another adapter with the same interface, but another interface, where `online` has a different meaning). But as you said, you don't know any guarantee that *AC* will be in the name. I *guess* it's very likely that it always is, but I also *guess* it's also somewhat unlikely that there will be a different interface with an `online` file, but what do I know?

In the end, I consider the `ls` call with `ac` matching slightly safer as it tends to error on the conservative side, while you could more easily weird undeterministic behaviour (in the sense that it's more likely to change across reboots) using the wildcard if there ever is non-AC interface with `online`.

>  grep with the wildcard doesn't have problems, if there are more than one interface with online; 

I was thinking about the case where there could be a (non-AC) interface with the `online` file.

**Comment by jo-so** [comment]
> I can't find any official statement that `io.popen` supports shell syntax like wildcards. Then again, there is nothing really other than "This function is system dependent and is not available on all platforms", so there is no guarantee for anything.

If `io.popen` wouldn't support shell-syntax, you couldn't use the space separation of arguments. This is shell-syntax, too. The kernel function to start programs `execve` requires an array of string arguments. With `"ls -1 "..pow` you're already enforcing shell-syntax. It's the difference between the C functions *system(3)* and *execve(2)*.

>  But as you said, you don't know any guarantee that AC will be in the name. I guess it's very likely that it always is, but I also guess it's also somewhat unlikely that there will be a different interface with an online file, but what do I know?

The kernel documentation *Documentation/ABI/testing/sysfs-class-power* suggests at least the strings *USB* and *UPS* in names. But these might not be common on consumer devices.

> > grep with the wildcard doesn't have problems, if there are more than one interface with online;
>
> I was thinking about the case where there could be a (non-AC) interface with the online file.

But *Documentation/ABI/testing/sysfs-class-power* says clearly: *Indicates if VBUS is present for the supply.* I read the document that the file is only used by non-batteries.

**Comment by coldfix** [comment]
> If `io.popen` wouldn't support shell-syntax, you couldn't use the space separation of arguments. This is shell-syntax, too. The kernel function to start programs `execve` requires an array of string arguments. With `"ls -1 "..pow` you're already enforcing shell-syntax. It's the difference between the C functions *system(3)* and *execve(2)*.

In principle, it's easy to do argument splitting followed by `execve` without a real shell and all the other fuss like wildcards, pipes, variable substitution etc. But as I said, there is no guarantee that either argument splitting nor wildcards will work. On the other hand, it's unlikely that lua is going to change their implementation anytime soon, so that was only a very minor concern...

> The kernel documentation *Documentation/ABI/testing/sysfs-class-power* suggests at least the strings USB and UPS in names. But these might not be common on consumer devices.

Thanks for the reference! That clears it up what is the correct approach: 

- iterate all folders in `/sys/class/power_supply`  (`"ls -1 " .. pow`)
- check the file `/sys/class/power_supply/<supply_name>/type`
- decide what to do based on the value "Battery", "UPS", "Mains", "USB"

**Comment by coldfix** [comment]
I think the best approach will be to add an argument for the ac adapter to the constructor and extend the `battery_widget.discover` function to return two tables, one with battery adapters, one with non-battery. `battery_widget.new` should then fallback to the first non-battery adapter if the argument is not passed.

**Comment by jo-so** [comment]
> In principle, it's easy to do argument splitting followed by execve without a real shell […]

I don't think so, because argument splitting involves quoting, i.e. `ls "a b"` can not simply done by a `split(" ")`. And there a two quoting characters and double quotes can be escaped inside of a double-quotes argument: `echo '1 2 3' "a 'x y\" b" \'z`.

I'm sorry, but I'm going to close this PR, because it's not the way **I** solve this problem.

**Comment by coldfix** [comment]
> I don't think so, because argument splitting involves quoting

So you think because argument splitting involves parsing quoted strings, it can only be done by shells? I guess the shells themselves (and almost any programming language) must then be implemented either by magic or by calling into yet other shells. :P

> I'm sorry, but I'm going to close this PR, because it's not the way I solve this problem.

Fair enough. Thanks anyway, your report helped uncover a potential issue and the correct way to detect the type of adapter.

**Pull request closed without merging**
