### PR TITLE
Notify when battery is completely charged

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by coldfix** [comment]
Thanks, can you also add a mention to the README?

**Comment by coldfix** [comment]
and cleanup the indentation for the code in the if block that you un-nested.

**Comment by ghost** [comment]
Done.

**Comment by coldfix** [comment]
Thanks! FYI, I have squash merged your changes. BTW: I meant cleanup the indentation of what's inside the if (i.e. such that the two `self:notify` calls are on the same indentation level) but I'll just quickly do it myself.

**Comment by ghost** [comment]
On Tue, Jul 17, 2018, 18:09 Thomas G. <notifications@github.com> wrote:

> Thanks! FYI, I have squash merged your changes. BTW: I meant cleanup the
> indentation of what's inside the if (i.e. such that the two self:notify
> calls are on the same indentation level) but I'll just quickly do it myself.
>
Oh, I overlooked it because the conditional was appearing more out of
place.

**Pull request merged**
