### PR TITLE
fix 102%

### PR DESCRIPTION
**Pull request by AbakarRamazanov**
I discovered value equal to 102%.
I don't know Lua language. But I think this decision fixed this problem.
Good luck.

### CODE REVIEW

**Comment by coldfix** [comment]
Hi, I have experienced as well that >100% can occur. This is due to the system reporting a higher charge than capacity. I'm not sure we should silence this, rather than simply reporting it exactly as the system reports.

**Comment by AbakarRamazanov** [comment]
Maybe so:
if r.present > 100 and r.present < 105 then
    r.present = 100
end

I don't know about permissible excess charge. But I think is it no create many problem. 

P.S. Excuse me for my English.

**Comment by coldfix** [comment]
I think I prefer it as is for me, at least for now - because then it just displays the quantity as reported by the system.

If you want to change it in your version, I recommend to use the shorter patch:

```lua
r.percent = math.min(100, r.percent)
```

which does the same as your lines.

**Edit:** .. except that your patch contains a syntax error due and the additional lower-bound.

**Comment by AbakarRamazanov** [comment]
Thank you :)

**Pull request closed without merging**
