### PR TITLE
Add the ability to specify the widget's font.

### PR DESCRIPTION
**Pull request by lmanul**

### CODE REVIEW

**Comment by coldfix** [comment]
Hey,

thanks! Can you rename to `widget_font` (I prefer short names) and add a short entry to the README. Also, I think you don't need to store it as a member variable, just assign directly to `widget.font = args.widget_font` or `widget:set_font(args.widget_font)` (even without the if-check should be enough, since it seems to be a NOP if nil).

Sorry to be so picky;)

By the way: which font are you using for your fancy unicodes?

One more question: Does this have access to all system fonts or just the ones defined for beautiful (trying a few, I got the impression that it doesn't know my system fonts..).

Best, Thomas

**Comment by lmanul** [comment]
No worries at all! It's your project, I'm totally expecting that you'll want things to blend into the existing state :-) Please don't hesitate to ask for more tweaks as needed.

I'm not sure what set of fonts this has access to, I'm using "Deja Vu Sans Mono" which seems to work great, I think it's the default, I'm only just tweaking the size.

**Comment by coldfix** [comment]
Ok, thanks for the info.

It would be best if you show in the README a valid font string including font size for the usage options (just take your own config) and remove the `self.widget_text_font` assignment.

PS: the unicode symbols from your other PR don't work for me with Deja Vu Sans Mono, so I'm not sure what's causing that. Do you have any ideas by any chance?

Personally, I lack any decent oversight over this topic since I'm completely overwhelmed and confused by the multitude of font configs on linux: tty (`/etc/vconsole.conf`), terminals (`~/.Xresources`), window manager (beautiful theme), gtk2 (`~/.gtkrc-2.0`), gtk3 (`~/.config/gtk-3.0/settings.ini`), qt (?), individual applications, fontconfig (`~/.config/fontconfig/`), tex, etc..

**Comment by coldfix** [comment]
Also, please squash your commits into a single one (or I will do when merging).

**Comment by lmanul** [comment]
Oops, sorry I had left that assignment around. Err, I think not only do I share your being overwhelmed by Linux font configs, but I am also overwhelmed by git's commit model (which should be obvious by now given my spurious merges and commits). I've tried squashing them but somehow the origin doesn't accept my push. If you can do any magic on your side, that would be awesome, and I promise to read up a bit more on git before my next pull request :-D

**Comment by coldfix** [comment]
No problem.

when you have squashed or otherwise modified your commit history, you can push with `git push -f` (force-push). But you should never do this on a published master branch.

I have squash-merged your commits. In order to synchronize, either fetch my new version (`git fetch`) and then reset your current state (`git reset origin/master`), or just clone the repo fresh.

Best, Thomas

**Comment by lmanul** [comment]
Thanks for putting up with my git-newbieness :-)

**Comment by coldfix** [comment]
No problem, you're doing great;)

**Pull request merged**
