### PR TITLE
Handle non existent battery

### PR DESCRIPTION
**Pull request by xarkes**
This patch allows the instantiation of a battery widget with an non-existent adapter. For instance some laptops have multiple battery slots which are not connected all the time.

### CODE REVIEW

**Comment by coldfix** [comment]
Hi, by letting the *adapter* argument unspecified, this module should already handle non-existent or multiple batteries. Did you have problems with this?

Anyway, if we really do need to merge this in order to make it work, it should be a one line patch:

```diff
@@ -159,7 +159,7 @@ function battery_widget:get_state()
￼                     or sysfs_names.discharging)
￼  
￼      local function read_trim(filename)
-        return trim(readfile(filename))
+        return trim(readfile(filename)) or ""
      end
￼  
￼      -- If there is no battery on this machine.
```

**Comment by xarkes** [comment]
Maybe non-existent is not the correct way to say it, I meant not plugged (so the file doesn't exist). I need to specify the adapter argument as I sometime have two batteries, one in BAT0 and the other in BAT1 :)
Ah yes of course, I'm not familiar with lua, let me fix this.

**Comment by coldfix** [comment]
I see, the sysfs files completely disappear when you remove the second battery, which isn't liked by the widget of course..

After your patch the widget will always show two entries, even if the second battery is unplugged, right? We can certainly merge this as a first step, but I guess it would be nicer to show the second battery only if it is plugged in, or similar. What do you think?


Can you rebase to make it a single commit and force push to the same branch?

**Comment by xarkes** [comment]
> After your patch the widget will always show two entries, even if the second battery is unplugged, right?

Yes I have:
```lua
mybat0 = battery_widget { adapter = "BAT0" }
mybat1 = battery_widget { adapter = "BAT1" }
```
When `BAT1` is not plugged this is what is printed:
2018-04-10-200730_97x22_scrot

> We can certainly merge this as a first step, but I guess it would be nicer to show the second battery only if it is plugged in, or similar. What do you think?

Yes there is always room for improvement, but this is good for my needs for now.

> Can you rebase to make it a single commit and force push to the same branch?

I think you can manually squash and rename the commits from the GitHub interface, but I will do it.

**Comment by coldfix** [comment]
Great thanks.

> I think you can manually squash and rename the commits from the GitHub interface, but I will do it.

I forgot about that... ;)

**Pull request merged**
