### PR TITLE
Add low battery notification

### PR DESCRIPTION
**Pull request by dokthar**
This add a low battery alert, the notification is done with naughty.

### CODE REVIEW

**Comment by coldfix** [comment]
HI,

thanks for the addition. I was thinking about adding something like this myself. Two questions:

- it looks like `self.alert` is never reset, so it will always reuse the same notification, right? Does this play nice with charging back over the alarm threshold, the notification timing out,  and then discharging below again?
- once the battery level is low, will the notification ever actually time out? (`update` is usually called on a regular interval and this leads to resetting the timeout, right?)

If this is correct, I'd prefer a check that creates the notification only once and updates the text if it still exists, but does not reset the timeout. When the battery level charges over the threshold level, it should reset `self.alert` and allow recreation of the notification. Or is there a reason to do it differently?

Also, I think `alert_threshold` will be easier to understand than `alert_trigger`.

**Comment by dokthar** [comment]
> it looks like self.alert is never reset, so it will always reuse the same notification, right? 

It will reuse the same notification unless the notification is discarded before the next update. This is done in line 257 by `destroy = function() self.alert = nil end` .

> going back over the alarm threshold and then going below again?

Going back over the threshold doesn't remove the notification.

> once the battery level is low, will the notification ever actually time out?

You are right It will not really time out because of the regular update.

> (update is usually called on a regular interval and this leads to resetting the timeout, right?)

Yes.

> If this is correct, I'd prefer a check that creates the notification only once and updates the text if it still exists, but does not reset the timeout. When the battery level charges over the threshold level, it should reset self.alert and allow recreation of the notification. Or is there a reason to do it differently?

The reason was to have a sort of reminder but it will be really annoying due to the frequent updates.
I will do the changes, It seem to be a better solution to warn only once until the notification time out or being dismissed.

Also I think it is better to reset the alert on charging.

> Also, I think alert_threshold will be easier to understand than alert_trigger.

Sure.

**Comment by coldfix** [comment]
> This is done in line 257 by `destroy = function() self.alert = nil end` .

Oh sorry, wasn't paying close enough attention.

> I will do the changes, It seem to be a better solution to warn only once until the notification time out or being dismissed.

Great, thanks! :)

**Comment by coldfix** [comment]
Works great!

**Pull request merged**
