### PR TITLE
Check if file exists before reading it

### PR DESCRIPTION
**Pull request by Scorfly**

### CODE REVIEW

**Comment by coldfix** [comment]
Hey, I'm a bit worried that this just delays potential errors until the corresponding value is used at some point down the line. If adding this, we should also handle the case that the input variables are nil.

**Comment by Scorfly** [comment]
I did this because on my computer one file does not exist : 
`    ac_state  = readfile(pre.."/AC/online")`

I totally understand your point of view. I'll check to update this later.

**Comment by Scorfly** [comment]
I just amended my commit to add check on mandatory values

if a mandatory file is missing the function get_state return nil

i would add a popup/notiffication to inform that a file is missing but https://awesome.naquadah.org does not work any more and every thing i found need to require naughty, so i did not for now

**Comment by coldfix** [comment]
This isn't satisfactory either: Assume one of the mandatory files is not found, then `get_state` returns `nil` and `update` crashes on the line `text =  percent .. "%"`, indiscriminately of which file wasn't found.

I think there are two options here:

1. crash immediately for missing "mandatory files" (using the readfile function as is) and only handle `ac_state` (+others?) differently with a checked function
2. try as best as we can, and leave out only missing information or in the display (or show, e.g. `???`)

What do you prefer?

**Comment by Scorfly** [comment]
I amended my commit

in `get_state()` i checked values but never formated it
in `uptdate()` I formatted value with `Err!` if they can not be displayed

**Comment by coldfix** [comment]
Great thanks.

**Pull request merged**
